/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.HashSet;
import java.util.Set;
//librerias de conexion
import java.sql.Connection;//conexion a BD
import java.sql.DriverManager;//driver de conexion
import java.sql.ResultSet;//resultado final de datos
import java.sql.ResultSetMetaData;//resultado de metadatos
import java.sql.SQLException;//Tratamiento de Errros de BD SQL
import java.sql.Statement;//Generador de sentencias SQL
import java.text.SimpleDateFormat;//Formatear datos
import java.util.Date;//fecha de sistema
import javax.swing.ImageIcon;//Tratamiento de imagenes
import javax.swing.JOptionPane;//ventanas emergentes
import javax.swing.table.DefaultTableModel;//tabla de datos
import pojos.Usuario;
/**
 *
 * @author danie
 */
public class eliminarUsuarios extends javax.swing.JFrame {

    public Connection cn;
    public Statement stmt;
    public ResultSet rs;
    
    /**
     * Creates new form eliminarUsuarios
     */
    public eliminarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupUsuario = new javax.swing.ButtonGroup();
        lblTituloVentana = new javax.swing.JLabel();
        lblTip1 = new javax.swing.JLabel();
        lblTip2 = new javax.swing.JLabel();
        panRol = new javax.swing.JPanel();
        optAdministrador = new javax.swing.JRadioButton();
        optVendedor = new javax.swing.JRadioButton();
        lblId = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloVentana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTituloVentana.setText("Eliminar usuarios");

        lblTip1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTip1.setText("Tip: Para eliminar un usuario primero seleccione el tipo de usuario a eliminar, introduce su ID ");

        lblTip2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTip2.setText("y da clic en el boton de borrar, se te pedirá que confirmes");

        panRol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        btnGroupUsuario.add(optAdministrador);
        optAdministrador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optAdministrador.setText("Administrador");

        btnGroupUsuario.add(optVendedor);
        optVendedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optVendedor.setText("Vendedor");

        javax.swing.GroupLayout panRolLayout = new javax.swing.GroupLayout(panRol);
        panRol.setLayout(panRolLayout);
        panRolLayout.setHorizontalGroup(
            panRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optAdministrador)
                .addGap(18, 18, 18)
                .addComponent(optVendedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panRolLayout.setVerticalGroup(
            panRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optAdministrador)
                    .addComponent(optVendedor)))
        );

        lblId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblId.setText("Id:");

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar usuario");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cafe3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTip1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTip2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdUsuario))
                            .addComponent(panRol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(lblTituloVentana)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloVentana)
                .addGap(18, 18, 18)
                .addComponent(lblTip1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTip2)
                .addGap(18, 18, 18)
                .addComponent(panRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(lblImg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void conectarBase(){
        try{ //inicia try
                Class.forName("com.mysql.jdbc.Driver");
                cn=DriverManager.getConnection("jdbc:mysql://localhost/bdproyectofinalis","root","");
                JOptionPane.showMessageDialog(null, "Conexion a BD OK\n\nLuna");
                stmt=cn.createStatement();//genera sentencias sobre objetos de base de datos
        }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Error de base de datos 1: \n"+ ex);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error de base de datos 2:"+ e);
        }
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (optAdministrador.isSelected()) {//if para usuario administrado
            int confirmaEliminacion=JOptionPane.showConfirmDialog(null,"¿De verdad quiere eliminar este usuario administrador?","Mensaje Importante",JOptionPane.YES_NO_OPTION);
            int confirmaBaja;
        
            if (confirmaEliminacion==0) {
                try {
                    conectarBase();
                    int usuarioBaja = Integer.parseInt(txtIdUsuario.getText());

                    confirmaBaja=stmt.executeUpdate("DELETE FROM tusuariosadmin WHERE idadmin = '"+usuarioBaja+"'");

                    if (confirmaBaja == 1){
                        JOptionPane.showMessageDialog(null, "Se dio de baja el usuario administrador de la BD\n\n"+usuarioBaja+"\nVerifica consulta");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error no existe id del usuario administrador en la BD\n\n"+usuarioBaja+"\nVerifica consulta");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar usuario administrador de la BD\n\n"+e);
                }
            } 
        } else if(optVendedor.isSelected()){
            int confirmaEliminacion=JOptionPane.showConfirmDialog(null,"¿De verdad quiere eliminar este usuario vendedor?","Mensaje Importante",JOptionPane.YES_NO_OPTION);
            int confirmaBaja;
        
            if (confirmaEliminacion==0) {
                try {
                    conectarBase();
                    int usuarioBaja = Integer.parseInt(txtIdUsuario.getText());

                    confirmaBaja=stmt.executeUpdate("DELETE FROM tusuariosvend WHERE idvend = '"+usuarioBaja+"'");

                    if (confirmaBaja == 1){
                        JOptionPane.showMessageDialog(null, "Se dio de baja el usuario administrador de la BD\n\n"+usuarioBaja+"\nVerifica consulta");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error no existe id del usuario administrador en la BD\n\n"+usuarioBaja+"\nVerifica consulta");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar usuario administrador de la BD\n\n"+e);
                }
            } 
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eliminarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGroupUsuario;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblTip1;
    private javax.swing.JLabel lblTip2;
    private javax.swing.JLabel lblTituloVentana;
    private javax.swing.JRadioButton optAdministrador;
    private javax.swing.JRadioButton optVendedor;
    private javax.swing.JPanel panRol;
    private javax.swing.JTextField txtIdUsuario;
    // End of variables declaration//GEN-END:variables
}
